### ISSUE TITLE
request the endpiont of OpenAI, 404 error

### ISSUE THREAD

**Issue by delai** [directus-labs/extension-ai-writer-operation#2]
I did some debugging and noticed an issue with the `request`  function from 'directus:api'.
Could you please help check this issue? Thank you very much.

<img width="513" alt="image" src="https://github.com/user-attachments/assets/ce7bfa97-e8e1-4e9b-af52-748e3d770f2a">

![image](https://github.com/user-attachments/assets/bf621a42-bf12-480f-8106-9eb466922323)

![image](https://github.com/user-attachments/assets/35be2249-26f6-4b27-a46d-bd8da63faf6a)

**Comment by binaryben** [comment]
Hi @delai. Have you added your OpenAI API key to the config for the extension?

**Comment by delai** [comment]
Aha, it looks like that. Thank you for your response.
